version: "3"

services:
  nodeseatd:
    image: cubetrain/seat:latest
    command: /opt/cubetrain/bin/nodeseatd.sh --data-dir /opt/cubetrain/bin/data-dir -e --http-alias=nodeseatd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodeseatd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeseat-data-volume:/opt/cubetrain/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keyseatd:
    image: cubetrain/seat:latest
    command: /opt/cubetrain/bin/keyseatd --wallet-dir /opt/cubetrain/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keyseatd:8900 --http-alias=localhost:8900
    hostname: keyseatd
    links:
      - nodeseatd
    volumes:
      - keyseatd-data-volume:/opt/cubetrain/bin/data-dir
    stop_grace_period: 10m

volumes:
 nodeseat-data-volume:
   external: true
 keyseatd-data-volume:
   external: true
